<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit86dad52224ed9e1b71960bb9ab8f2f6a
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Bluehost\Plugin\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Bluehost\Plugin\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit86dad52224ed9e1b71960bb9ab8f2f6a', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Bluehost\Plugin\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit86dad52224ed9e1b71960bb9ab8f2f6a', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Bluehost\Plugin\Composer\Autoload\ComposerStaticInit86dad52224ed9e1b71960bb9ab8f2f6a::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
